### ISSUE TITLE
java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by lintghi** [fusesource/hawtdispatch#32]
could u help me to find out why i got this exception when receiving message?

java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
    at sun.nio.ch.IOUtil.read(IOUtil.java:171)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
    at org.fusesource.hawtdispatch.transport.AbstractProtocolCodec.read(AbstractProtocolCodec.java:326)
    at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:706)
    at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:588)
    at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
    at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
    at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

**Comment by lintghi** [comment]
it occur when receiving message and can not auto recovery like reconnection. i must restart message consumer application to keep on receive.
